# version: '3.8'

# services:
#   django:
#     container_name: django
#     build:
#       context: ../django-celery #project folder name
#       dockerfile: Dockerfile
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes: # store data into the container which mounts local directory into the docker container
#       - ../django-celery:/usr/src/app/ 
#     ports:
#       - 8001:8000
#     environment:
#       - DEBUG=1
#       - SECRRET_KEY=87sdfga8sdfasdfa8sdf8988sadf
#       - ALLOWED_HOSTS= localhost,127.0.0.1

version: '3.8'

services:
  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=87sdfga8sdfasdfa8sdf8988sadf
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: .
    command: celery --app=core worker -l INFO -Q celery,celery:1,celery:2,celery3  # Assuming 'core' is where celery.py is located
    # command: celery --app=core worker -l INFO -Q queue1  # Assuming 'core' is where celery.py is located
    volumes:
      - .:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=87sdfga8sdfasdfa8sdf8988sadf
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
      - django
  
  celery-beat:
    container_name: celery-beat
    build:
      context: .
    command: celery --app=core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=87sdfga8sdfasdfa8sdf8988sadf
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
      - django

  # celeryworker:
  #   container_name: celeryworker
  #   build:
  #     context: ./celeryworker
  #     dockerfile: Dockerfile
  #   command: celery -A celeryconfig worker -l INFO -Q queue2 
  #   #celeryconfig is the file name inside celeryworker directory
  #   volumes:
  #     - ./celeryworker:/usr/src/app
  #   depends_on:
  #     - redis
  #     - django
